### PR TITLE
Bad commit

### PR DESCRIPTION
**Pull request by Alexgoon**

### CODE REVIEW

**Comment by Alexgoon** [comment]
[BUILDING ERROR]
	OUTPUT: MainWindow.xaml.cs(24,13): error CS0165: Use of unassigned local variable 'counter' [C:\Program Files (x86)\Jenkins\workspace\TestExample_15.1.5-15.1.7\CS\Example\Example.csproj]

**Comment by Alexgoon** [comment]
[BUILDING ERROR]
	OUTPUT: MainWindow.xaml.cs(24,13): error CS0165: Use of unassigned local variable 'counter' [C:\Program Files (x86)\Jenkins\workspace\TestExample_15.1.5-15.1.7\CS\Example\Example.csproj]

**Comment by Alexgoon** [comment]
[BUILDING ERROR]
	OUTPUT: MainWindow.xaml.cs(24,13): error CS0165: Use of unassigned local variable 'counter' [C:\Program Files (x86)\Jenkins\workspace\TestExample_15.1.5-15.1.7\CS\Example\Example.csproj]
