### PR TITLE
Bad commit

### PR DESCRIPTION
**Pull request by Alexgoon**

### CODE REVIEW

**Comment by Alexgoon** [comment]
[BUILDING ERROR]
	OUTPUT: obj\Debug\App.g.cs(12,22): error CS0234: The type or namespace name 'DXBinding' does not exist in the namespace 'DevExpress.Xpf' (are you missing an assembly reference?) [D:\progs\Jenkins\jobs\TestExample_15.1.5-15.1.7\workspace\CS\Example\Example.csproj]
obj\Debug\MainWindow.g.cs(12,22): error CS0234: The type or namespace name 'DXBinding' does not exist in the namespace 'DevExpress.Xpf' (are you missing an assembly reference?) [D:\progs\Jenkins\jobs\TestExample_15.1.5-15.1.7\workspace\CS\Example\Example.csproj]
